In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("DateFruit_Dataset.csv")

In [3]:
df.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 898 entries, 0 to 897
Data columns (total 35 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   AREA           898 non-null    int64
 1   PERIMETER      898 non-null    float64
 2   MAJOR_AXIS     898 non-null    float64
 3   MINOR_AXIS     898 non-null    float64
 4   ECCENTRICITY   898 non-null    float64
 5   EQDIASQ        898 non-null    float64
 6   SOLIDITY       898 non-null    float64
 7   CONVEX_AREA    898 non-null    int64
 8   EXTENT         898 non-null    float64
 9   ASPECT_RATIO   898 non-null    float64
 10  ROUNDNESS      898 non-null    float64
 11  COMPACTNESS    898 non-null    float64
 12  SHAPEFACTOR_1  898 non-null    float64
 13  SHAPEFACTOR_2  898 non-null    float64
 14  SHAPEFACTOR_3  898 non-null    float64
 15  SHAPEFACTOR_4  898 non-null    float64
 16  MeanRR         898 non-null    float64
 17  MeanRG         898 non-null    float64
 18  MeanRB         898 non-null    float64
 19  StdDevRR       898 non-null    float64
 20  StdDevRG       898 non-null    float64
 21  StdDevRB       898 non-null    float64
 22  SkewRR         898 non-null    float64
 23  SkewRG         898 non-null    float64
 24  SkewRB         898 non-null    float64
 25  KurtosisRR     898 non-null    float64
 26  KurtosisRG     898 non-null    float64
 27  KurtosisRB     898 non-null    float64
 28  EntropyRR      898 non-null    int64
 29  EntropyRG      898 non-null    int64
 30  EntropyRB      898 non-null    int64
 31  ALLdaub4RR     898 non-null    float64
 32  ALLdaub4RG     898 non-null    float64
 33  ALLdaub4RB     898 non-null    float64
 34  Class          898 non-null    str
dtypes: float64(29), int64(5), str(1)
memory usage: 250.5 KB

In [5]:
df.shape

(898, 35)

In [6]:
X = df.drop("Class" , axis = 1)
y = df["Class"]

In [7]:
df["Class"].unique()

<ArrowStringArray>
['BERHI', 'DEGLET', 'DOKOL', 'IRAQI', 'ROTANA', 'SAFAVI', 'SOGAY']
Length: 7, dtype: str

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [9]:
y = le.fit_transform(y)

In [10]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
                                        X, 
                                        y, 
                                        test_size=0.2, 
                                        random_state=42
                                    )

In [12]:
X.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,0.6019,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,0.4134,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,0.9183,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,1.8028,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,0.8865,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666

In [13]:
X.shape

(898, 34)

In [14]:
y.shape

(898,)

In [15]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [16]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [17]:
import torch 
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader , TensorDataset

In [18]:
X_train_tensor = torch.tensor(X_train_scaled , dtype = torch.float32)
X_test_tensor = torch.tensor(X_test_scaled , dtype = torch.float32)

Y_train_tensor = torch.tensor(y_train , dtype = torch.long)
Y_test_tensor = torch.tensor(y_test , dtype = torch.long)

In [19]:
train_dataset = TensorDataset(X_train_tensor , Y_train_tensor)
test_dataset = TensorDataset(X_test_tensor , Y_test_tensor)

In [20]:
train_loader = DataLoader(train_dataset , batch_size = 32 , shuffle = True )
test_loader = DataLoader(test_dataset , batch_size = 32 )

In [45]:
class ANN(nn.Module): 
    def __init__(self): 
        super(ANN , self).__init__() 
        
        self.model = nn.Sequential( 
            nn.Linear(X.shape[1] , 64), 
            nn.ReLU(),
            
            nn.Linear(64 , 64), 
            nn.ReLU(), 
            
            nn.Linear(64 , 7) 
        ) 
        
    def forward(self , X):
        return self.model(X)

In [46]:
model = ANN()

criteria = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())

In [47]:
epochs = 100
for epoch in range(epochs):
    model.train()

    running_loss = 0.0

    for xb, yb in train_loader:
        optimizer.zero_grad()
        
        outputs = model(xb)
        loss = criteria(outputs, yb)
        loss.backward()
        optimizer.step() 

        running_loss += loss.item()

    train_loss = running_loss / len(train_loader)

    print(f"epoch = {epoch+1}/{epochs}, loss = {train_loss}")

epoch = 1/100, loss = 1.6639302398847498
epoch = 2/100, loss = 1.040613741978355
epoch = 3/100, loss = 0.6940081987691962
epoch = 4/100, loss = 0.5431696668915127
epoch = 5/100, loss = 0.4522132750438607
epoch = 6/100, loss = 0.39429074655408447
epoch = 7/100, loss = 0.35041704449964606
epoch = 8/100, loss = 0.313603765938593
epoch = 9/100, loss = 0.2932782429067985
epoch = 10/100, loss = 0.26307547286800714
epoch = 11/100, loss = 0.24871320828147556
epoch = 12/100, loss = 0.23226172574188397
epoch = 13/100, loss = 0.2208984309564466
epoch = 14/100, loss = 0.21358296275138855
epoch = 15/100, loss = 0.20389833074548971
epoch = 16/100, loss = 0.1929235448655875
epoch = 17/100, loss = 0.18372852322847946
epoch = 18/100, loss = 0.1727710006677586
epoch = 19/100, loss = 0.16530637961366904
epoch = 20/100, loss = 0.1639394502600898
epoch = 21/100, loss = 0.1584021555988685
epoch = 22/100, loss = 0.14824788628712945
epoch = 23/100, loss = 0.1408928733157075
epoch = 24/100, loss = 0.13525061017793158
epoch = 25/100, loss = 0.1280136946183832
epoch = 26/100, loss = 0.13035163720664772
epoch = 27/100, loss = 0.12320423693112705
epoch = 28/100, loss = 0.12469710020915321
epoch = 29/100, loss = 0.12000108251105183
epoch = 30/100, loss = 0.11558003189123195
epoch = 31/100, loss = 0.11661100581936214
epoch = 32/100, loss = 0.11686088120483834
epoch = 33/100, loss = 0.10997779796952786
epoch = 34/100, loss = 0.10930552932879199
epoch = 35/100, loss = 0.10723512927475183
epoch = 36/100, loss = 0.10122902148767658
epoch = 37/100, loss = 0.09774308983722459
epoch = 38/100, loss = 0.10576248914003372
epoch = 39/100, loss = 0.09608002962625545
epoch = 40/100, loss = 0.08953606952791629
epoch = 41/100, loss = 0.08865048574364703
epoch = 42/100, loss = 0.08719483317564362
epoch = 43/100, loss = 0.0852408021202554
epoch = 44/100, loss = 0.08083717395430026
epoch = 45/100, loss = 0.09682995781464421
epoch = 46/100, loss = 0.09156035469925922
epoch = 47/100, loss = 0.08093123255378526
epoch = 48/100, loss = 0.07514294714707395
epoch = 49/100, loss = 0.07897666866040748
epoch = 50/100, loss = 0.07906582028321597
epoch = 51/100, loss = 0.07640539372906736
epoch = 52/100, loss = 0.07292520113127388
epoch = 53/100, loss = 0.07160243023510861
epoch = 54/100, loss = 0.07143943643440372
epoch = 55/100, loss = 0.06862097233533859
epoch = 56/100, loss = 0.0676400111583264
epoch = 57/100, loss = 0.08255333315743052
epoch = 58/100, loss = 0.0702355002336528
epoch = 59/100, loss = 0.059675703432572925
epoch = 60/100, loss = 0.06117683321075595
epoch = 61/100, loss = 0.06649666506311168
epoch = 62/100, loss = 0.0637883311137557
epoch = 63/100, loss = 0.06347045419818681
epoch = 64/100, loss = 0.06262844468912353
epoch = 65/100, loss = 0.05668604155273541
epoch = 66/100, loss = 0.05420495784315078
epoch = 67/100, loss = 0.05543570997922317
epoch = 68/100, loss = 0.057497412209277565
epoch = 69/100, loss = 0.05400258659020714
epoch = 70/100, loss = 0.052956175565233694
epoch = 71/100, loss = 0.048153596262083105
epoch = 72/100, loss = 0.052674719699375004
epoch = 73/100, loss = 0.04913367124517327
epoch = 74/100, loss = 0.04739008524009715
epoch = 75/100, loss = 0.04666863147007382
epoch = 76/100, loss = 0.04089993999704071
epoch = 77/100, loss = 0.04574411269277334
epoch = 78/100, loss = 0.04344212488554742
epoch = 79/100, loss = 0.04017741808100887
epoch = 80/100, loss = 0.04200362096257184
epoch = 81/100, loss = 0.04733280776797429
epoch = 82/100, loss = 0.05883701423021114
epoch = 83/100, loss = 0.04646336649666014
epoch = 84/100, loss = 0.04372534592150022
epoch = 85/100, loss = 0.03989021337348158
epoch = 86/100, loss = 0.03786872161309356
epoch = 87/100, loss = 0.03277611467258438
epoch = 88/100, loss = 0.034540345588618
epoch = 89/100, loss = 0.03487874986603856
epoch = 90/100, loss = 0.03251015180316956
epoch = 91/100, loss = 0.031341654592720064
epoch = 92/100, loss = 0.03443458042633922
epoch = 93/100, loss = 0.034506445122963705
epoch = 94/100, loss = 0.03241643625433031
epoch = 95/100, loss = 0.030976581265744957
epoch = 96/100, loss = 0.03087729573978678
epoch = 97/100, loss = 0.026662263381497367
epoch = 98/100, loss = 0.03141344905547474
epoch = 99/100, loss = 0.02942568970763165
epoch = 100/100, loss = 0.029081081202172714

In [49]:
model.eval()

total = 0
correct = 0 

with torch.no_grad() :
    for xb , yb in test_loader :
        outputs = model(xb)
        max_out , pred_value = torch.max(outputs , 1)

        correct += (pred_value == yb).sum().item()
        total += yb.size(0)

print(f"Total values :-> {total}")
print(f"Correct prediction :-> {correct}")

Total values :-> 180
Correct prediction :-> 168

In [52]:
print(f"Accuracy Score :-> {(correct/total)*100} %")

Accuracy Score :-> 93.33333333333333 %